---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: golang:1.11
  commands:
  - go test -v -cover ./...
  - CGO_ENABLED=0 go build -o release/linux/amd64/drone-kubernetes-secrets github.com/drone/drone-kubernetes-secrets/cmd/drone-kubernetes-secrets

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: drone/kubernetes-secrets
    username:
      from_secret: docker_username

...
